typography_spectrum: 0.12378831300884485
color:
  brandStrength: 0.8315072054974735
  lightness: 0.9284227197058499
  saturation: 0.6597471288405359
  rhythmicContrast: 0.44447571667842567
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.32996589224785566
name: rudolfgreger
title: die L.E.D.
description: 'rudolf greger Ã¼ber design, management & society'
